<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>5d16ae19-0d43-4708-8318-cfdce74734b1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qwdqwizardmaingridcontainere-table&quot;)/tbody[1]/tr[@class=&quot;e-treegridrows gridrowIndex1level1  e-templaterow   e-alt-row&quot;]/td[@class=&quot;e-intend e-rowcell e-templatecell&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
