<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_externalContentHost4</name>
   <tag></tag>
   <elementGuidId>73025ebb-d316-45b3-b533-f11558f2b0e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[count(. | //*[@id = 'externalContentHost4']) = count(//*[@id = 'externalContentHost4'])][count(. | //*[@name = 'externalContentHost4']) = count(//*[@name = 'externalContentHost4'])][count(. | //*[@src = 'http://asna:8028/VSOInteGreat4TFS/IndexForVSTS?selectedTab=qwizard&amp;adminHubId=collection-level-admin-hub']) = count(//*[@src = 'http://asna:8028/VSOInteGreat4TFS/IndexForVSTS?selectedTab=qwizard&amp;adminHubId=collection-level-admin-hub'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>external-content-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>externalContentHost4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>externalContentHost4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://asna:8028/VSOInteGreat4TFS/IndexForVSTS?selectedTab=qwizard&amp;adminHubId=collection-level-admin-hub</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;externalContentHost4&quot;)</value>
   </webElementProperties>
</WebElementEntity>
