<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_12364</name>
   <tag></tag>
   <elementGuidId>bedcffec-59cf-462a-88ca-b744392d9da6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>work-item-form-headerContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12364</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vss_189&quot;)/div[@class=&quot;witform-layout&quot;]/div[@class=&quot;witform-layout-scrollable-frame&quot;]/div[@class=&quot;witform-layout-content-container&quot;]/div[@class=&quot;work-item-form-main-header&quot;]/div[@class=&quot;work-item-form-headerContent&quot;]</value>
   </webElementProperties>
</WebElementEntity>
