<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RTM11.7.2-scrum</name>
   <tag></tag>
   <elementGuidId>339aa5be-f00b-49e6-baa9-5c2656dd77d0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Link root_a3f45c6b project-team-name ms-fontSize-m isEnabled_a3f45c6b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tfs/QA%20Collection%202/RTM11.7.2-scrum</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Project 'RTM11.7.2-scrum'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RTM11.7.2-scrum</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vss_1&quot;)/div[@class=&quot;internal-content-host&quot;]/div[@class=&quot;project-hub-component&quot;]/div[@class=&quot;project-list-component&quot;]/div[@class=&quot;ms-Fabric ms-font-m hub-view-component&quot;]/div[@class=&quot;hub-view-content&quot;]/ul[@class=&quot;hub-groups&quot;]/li[1]/div[@class=&quot;hub-group&quot;]/div[@class=&quot;ms-Viewport&quot;]/div[@class=&quot;ms-DetailsList root_1c1400f0&quot;]/div[1]/div[2]/div[@class=&quot;ms-FocusZone focusZone_1c1400f0&quot;]/div[@class=&quot;ms-SelectionZone&quot;]/div[@class=&quot;ms-List&quot;]/div[@class=&quot;ms-List-surface&quot;]/div[@class=&quot;ms-List-page&quot;]/div[@class=&quot;ms-List-cell&quot;]/div[@class=&quot;is-active&quot;]/div[@class=&quot;ms-DetailsRow ms-u-fadeIn400 root_8929bb92&quot;]/div[@class=&quot;ms-FocusZone&quot;]/div[@class=&quot;ms-DetailsRow-fields fields_8929bb92&quot;]/div[@class=&quot;ms-DetailsRow-cell cell_8929bb92 project-column-title&quot;]/div[@class=&quot;project-team-title&quot;]/a[@class=&quot;ms-Link root_a3f45c6b project-team-name ms-fontSize-m isEnabled_a3f45c6b&quot;]</value>
   </webElementProperties>
</WebElementEntity>
