<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FAQ</name>
   <tag></tag>
   <elementGuidId>41cc74f4-f6bb-440b-8a93-4c3d2ac9d239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ig-dashboard-container > div.container-fluid > div > div:nth-child(2) > div:nth-child(1) > div > div:nth-child(2) > div > ul > li:nth-child(4) > span > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>db-list-item-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dashboardListClicked('inteGREAT.Web.QWizard','http://arsalanmushtaq:8028/QWizard/QWizard/QWizard','ig-qwizard-container');return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig-dashboard-container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-3 col-md-3&quot;]/div[1]/div[1]/div[2]/div[1]/ul[@class=&quot;db-areatitle-content-padding&quot;]/li[@class=&quot;db-list-item&quot;]/span[@class=&quot;db-list-item-text&quot;]/a[@class=&quot;db-list-item-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
