<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ss</description>
   <name>li</name>
   <tag></tag>
   <elementGuidId>b72e03a6-2829-4f8c-8192-051819bcccf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>(&quot;li[title='DefaultCollection']&quot;)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Folder/Page_Modern Requirements4TFS 2018/CollectionContainer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
</WebElementEntity>
